version: "3"
services:
  nginx: 
    image: openresty/openresty
    ports: 
      - 8080:80
    volumes:
      - ./nginxconf/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginxconf/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
  au:
    image: otomato/au
    ports: 
      - 3100
  syslog:
    image: kuzishai/syslog-server-udp:v0.2
    ports:
      - 9898
